name: Gerar PDF do Currículo

on:
  push:
    branches:
      - main
    paths:
      # Só roda se o arquivo .md mudar
      - 'README.md' 

jobs:
  build-pdf:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        with:
          # Precisamos "puxar" o histórico para poder "empurrar" (push)
          fetch-depth: 0 

      # 2. Instalar Pandoc e LaTeX
      - name: Instalar Pandoc e dependências LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex

      # 3. Criar pasta 'build'
      - name: Criar pasta para o PDF
        run: mkdir -p build

      # 4. Converter Markdown para PDF (Sabemos que isso funciona)
      - name: Converter Markdown para PDF
        run: |
          pandoc README.md \
            -o build/curriculo.pdf \
            --pdf-engine=xelatex \
            -V geometry:margin=1in

      # -----------------------------------------------------------------
      # SUBSTITUÍMOS O ROBÔ CULPADO POR PASSOS MANUAIS
      # -----------------------------------------------------------------

      # 5. Configurar o Git
      - name: Configurar o Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # 6. Adicionar arquivos e fazer o Commit
      - name: Adicionar e Commitar o PDF
        run: |
          # Adiciona o .gitattributes PRIMEIRO para garantir que ele seja lido
          git add .gitattributes 
          # Adiciona o novo PDF
          git add build/curriculo.pdf
          
          # Verifica se há mudanças. Se houver, faz o commit.
          # Isso evita erros caso o PDF não tenha mudado
          if ! git diff --cached --quiet; then
            git commit -m "chore: Atualiza currículo em PDF [BOT]"
          else
            echo "Nenhuma mudança no PDF para commitar."
          fi

      # 7. Enviar o Push para o repositório
      - name: Enviar (Push) o PDF
        run: git push origin main